theme: minima
title: In Otter Words
author: Mr. OtterWords
description: Understanding the ethics of immigration controls.
social:
  bluesky: @otterwords.bsky.social
  youtube: @inotterwords6115
  # Add other social media platforms as needed
